### PR TITLE
Adding support for multiple records to lite

### PR DESCRIPTION
**Pull request by ianabc**
This isn't a finished pull request, it's just for discussion.

At the moment [wos.utils._get_records](https://github.com/enricobacis/wos/blob/45774fe9cdb62e224214659da2987c6c0ded7981/wos/utils.py) returns a single record (the first) when there might be multiple results in the XML. the pull request just goes one level up in the XML to display all of the records returned by the search, once at [line 13](https://github.com/enricobacis/wos/blob/45774fe9cdb62e224214659da2987c6c0ded7981/wos/utils.py#L13) and again at [line 36](https://github.com/enricobacis/wos/blob/45774fe9cdb62e224214659da2987c6c0ded7981/wos/utils.py#L36).

I'm not really familiar with the schema so I'm not sure about how to handle this case better.

### CODE REVIEW

**Comment by enricobacis** [comment]
It's so strange that they made the lite and premium services to act so differently. I would expect only the output data to be different, but not the format. By the way you are correct, I will merge it and improve a bit, and let inform you when to test it again.

Thanks

**Comment by zuphilip** [comment]
Is this superseeded by the [wos-lite](https://github.com/enricobacis/wos/tree/wos-lite) branch?

**Comment by enricobacis** [comment]
Yes I eventually plan to merge that branch in master. I just need testers

**Comment by enricobacis** [comment]
Closing this since the wos-lite branch was merged.

**Pull request closed without merging**
