### PR TITLE
Update company name in docs

### PR DESCRIPTION
**Pull request by gneissone**
The Web of Science and its APIs are under the Clarivate brand name. This pull request updates the documentation to reflect the change.

Note - this does not update the PyPi metadata. If I understand correctly, the description on PyPi cannot be updated unless a new version of the package is released. 

Thank you!

### CODE REVIEW

**Comment by enricobacis** [comment]
Thanks Ben,

Could you add a commit to this PR and bump up the version in https://github.com/enricobacis/wos/blob/master/VERSION to 0.2.6? This would also trigger a new version to be released on PyPI

Thanks!

**Comment by enricobacis** [comment]
I merged the PR and created a tag for it so that PyPI should release a new version, if that doesn't happen within a few hours, please comment here and I'll manually force a new release.

Thanks

**Comment by enricobacis** [comment]
Ok, I see it updated on PyPI

**Comment by gneissone** [comment]
Awesome, thanks.

**Comment by enricobacis** [comment]
Hi @gneissone, I noticed that version 0.2.6 was removed from PyPI because some tests were breaking, I did the minimal change (dropped a few configuration lines) to be able to release 0.2.7 so that also on PyPI the correct name is shown. I also added a disclaimer to mention that I'm not affiliated with Clarivate and that the rights are reserved to the owners. 

This library is now unsupported and unmaintained, but I assume that Clarivate is fine having this code still here based on your previous message, but please do confirm this.

**Comment by gneissone** [comment]
Sounds good. FYI the latest word I'm hearing is that the SOAP WoS API will be retired sometime in 2022. The RESTful API has been available for a couple years now so hopefully those dependent on the API will have had time to migrate. There will be a formal announcement with details once it is official, of course.

**Pull request merged**
